name: CI Status

on:
  pull_request:
    branches: [main]

jobs:
  # CIステータスの統合チェック
  ci-status:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: []  # 他のワークフローの完了を待つ場合はここに追加

    steps:
      - name: CI Status
        run: |
          echo "✅ All CI checks must pass before merging to main branch"
          echo "This job serves as a status check for branch protection rules"
