name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: food-exploration-map:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker container
      run: |
        docker run -d --name test-app \
          -e NODE_ENV=production \
          -e GOOGLE_PLACES_API_KEY=test_key \
          -e GOOGLE_DIRECTIONS_API_KEY=test_key \
          -e GEMINI_API_KEY=test_key \
          -e NEXT_PUBLIC_APP_URL=http://localhost:3000 \
          -p 3000:3000 \
          food-exploration-map:test
        
        # Wait for container to start
        sleep 15
        
        # Test if the application is running
        curl -f http://localhost:3000 || exit 1
        
        # Test API endpoints
        curl -f http://localhost:3000/api/places || exit 1
        curl -f http://localhost:3000/api/stations || exit 1
        curl -f http://localhost:3000/api/mood || exit 1
        
        # Stop container
        docker stop test-app